# Generated by Django 6.0.4 on 2026-04-16 12:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0006_review'),
    ]

    operations = [
        migrations.AddField(
            model_name='room',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='room',
            name='features',
            field=models.TextField(blank=True, null=True),
        ),
    ]
