# Generated by Django 6.0.4 on 2026-04-22 08:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0011_otp'),
    ]

    operations = [
        migrations.DeleteModel(
            name='OTP',
        ),
    ]
